---

- name: Install Slack Dependencies
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - gconf2
    - gconf-service
    - gvfs-bin
    - libappindicator1

- name: install Slack
  command: snap install slack
