---

- name: Download Zoom Deb
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb

- name: Install Zoom Prerequisites
  apt:
    name: libxcb-xtest0

- name: Extract Zoom Deb
  command: dpkg -i /tmp/zoom_amd64.deb

- name: install Zoom
  command: apt -f install
