---

- name: Configure the Wine PPA
  apt_repository: repo="ppa:ubuntu-wine/ppa" state=present

- name: Install Wine
  apt: pkg=wine state=latest



---

- name: Add Wine GPG key
  apt_key: url=https://dl.winehq.org/wine-builds/Release.key

- name: Add Wine APT repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.winehq.org/wine-builds/ubuntu/ {{ansible_distribution_release}} stable

- name: Install Wine 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: yes
  with_items:
    - winehq-stable

